name: Install Yarn
description: Run yarn install

inputs:
  cwd:
    required: false
    type: string
    default: '.'

env:
  NODE_ENV: production
  HUSKY: '0'

runs:
  using: 'composite'

  steps:
    - name: ⚙️ Expose yarn config as "$GITHUB_OUTPUT"
      id: yarn-config
      shell: bash
      working-directory: ${{ inputs.cwd }}
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
      run: |
        echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        echo "CURRENT_NODE_VERSION="node-$(node --version)"" >> $GITHUB_OUTPUT
        echo "CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's,/,-,g')" >> $GITHUB_OUTPUT
        echo "NPM_GLOBAL_CACHE_FOLDER=$(npm config get cache)" >> $GITHUB_OUTPUT

    - name: Cache rotation keys
      id: cache-rotation
      shell: bash
      run: |
        echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Setup yarn cache
      with:
        path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
        key: ${{ runner.os }}-yarn-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

    - name: 📥 Install dependencies
      shell: bash
      run: yarn config set network-timeout 600000 -g && yarn install --production --frozen-lockfile
