name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: 🧩 Build with ${{ matrix.node-version }} for ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: 📦 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: 📥 Install dependencies
        uses: ./nodejs/actions/pnpm-install

      - name: 🏗️ Build
        run: pnpm build
