name: Verify commits

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  verify-pr:
    name: 💻 Verify commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
