name: Update dependencies

on:
  workflow_call:
    inputs:
      nvmrc-path:
        required: true
        type: string

jobs:
  update:
    name: 📦 Update all dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: 📦 Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ inputs.nvmrc-path }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm packages:upgrade
      - run: pnpm security:audit
      - run: pnpm security:audit:fix
      - run: pnpm lint:fix
      - run: pnpm build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'ci: update dependencies to the latest version'
          title: 'Update dependencies to the latest version'
