name: Verify Commits

on:
  workflow_call:

jobs:
  commitlint:
    name: 💻 Verify commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Ensures the full history is available for commit comparison

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.nvmrc-path }}

      - uses: ajrly/gh-workflow-template/.github/actions/pnpm-install@main

      # Validate PR commits with commitlint
      - if: github.event_name == 'pull_request'
        name: Validate PR commits with commitlint
        run:
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{
          github.event.pull_request.head.sha }} --verbose
